### ISSUE TITLE
java.io.IOException: stream is closed

### ISSUE THREAD

**Issue by jos76** [adlnet/jxapi#12]
I'm trying to get statements from an LRS with the following code: 
```java
ArrayList<Statement> statements = new ArrayList<>();
Actor actor = new Agent(null, "mailto:me@example.com");

StatementClient client = new StatementClient(
        "https://my.lrs.com/TCAPI/statements",
        "lrs_username",
        "lrs_password").filterByActor(actor);

StatementResult results = client.getStatements();
statements.addAll(results.getStatements());
while (results.hasMore()) {
    results = client.getStatements(results.getMore());
    statements.addAll(results.getStatements());
}
```
When executing this code I get the following error:
```java
java.io.IOException: stream is closed
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.ensureOpen(HttpURLConnection.java:3308)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3333)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at gov.adlnet.xapi.client.BaseClient.issueGet(BaseClient.java:212)
	at gov.adlnet.xapi.client.StatementClient.getStatements(StatementClient.java:156)
```

**Comment by jos76** [comment]
This seems to be an endpoint issue. Could possibly throw a more descriptive exception or add better error handling.
