### ISSUE TITLE
addFilter is not working properly

### ISSUE THREAD

**Issue by Rialakshmi** [adlnet/jxapi#33]
Hi , I have used  the code given by you below. addFilter seemed to be working, but when I tested with some random value as filter, it is fetching other statements (which does not fall in Filter). Please check the code by posting many statements and try to apply filter. 
    public void testGetStatement() throws FileNotFoundException, IOException {
        Properties p = new Properties();
        p.load(new FileReader(new File("../jxapi/src/test/java/config/config.properties")));
        lrs_uri = p.getProperty("lrs_uri");
        username = p.getProperty("username");
        password = p.getProperty("password");
        mbox = p.getProperty("mbox");
        
        StatementClient client = new StatementClient(lrs_uri, username, password);
        
        Statement stmnt = new Statement(new Agent("test", mbox), 
                new Verb("http://example.com/tested"), 
                new Activity("http://example.com/" + UUID.randomUUID().toString()));
        
        HashMap<String, JsonElement> extension = new HashMap<String, JsonElement>();
        String room100key = "http://example.com/class_room_100";
        extension.put(room100key,  new JsonPrimitive("Math"));
        String room110key = "http://example.com/class_room_110";
        extension.put(room110key,  new JsonPrimitive("Science"));
        String room120key = "http://example.com/class_room_120";
        extension.put(room120key,  new JsonPrimitive("History"));
        Context context = new Context();
        context.setExtensions(extension);
        
        stmnt.setContext(context);
        client.putStatement(stmnt, stmnt.getId());
        
        client.addFilter(room120key, extension.get(room120key).getAsString()).getStatements();
    }
}

**Comment by ljwolford** [comment]
Can you print out the full URL of the request that jXAPI is creating?

**Comment by Rialakshmi** [comment]
Yeah I tried... Previously it was working.. Today I ran the code, its fetching wrong results.

**Comment by ljwolford** [comment]
Hmm, can you send me the full URL of the request it is making? If it is the same as before with the previous issue, then I think it is a problem on the LRS side. jXAPI is only responsible for building the query path of the request. Once again as a reminder, querying by extensions makes the LRS non-conformant and is out of scope.

**Comment by Rialakshmi** [comment]
I use Learning Locker BYW. I cannot send the exact URL,then it will become a security issue. filterBySince also not fetching correct details(filtered).

**Comment by ljwolford** [comment]
Can you just send the path then?

**Comment by Rialakshmi** [comment]
path?

**Comment by Rialakshmi** [comment]
Could you please clarify which path you want?

**Comment by ljwolford** [comment]
Just your query path when trying to query by since and your extension, not the full URL since it would be a security issue then.
scheme://host/path?query <--

**Comment by Rialakshmi** [comment]
I am trying with the same code. Its not working. Can you please test with set of statements with different values and try to apply filter? 

Agent agent=new Agent();
            agent.setName("test");
            agent.setMbox("mailto:test@gmail.com");
            Statement stmnt = new Statement(agent,
                    new Verb("http://example.com/tested"),
                    new Activity("http://example.com/" + UUID.randomUUID().toString()));
            String date = "9/26/2016" + " " + "15:50:11";
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
            sdf.setTimeZone(TimeZone.getTimeZone("GMT"));
            Date date2 = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss").parse(date);
            String timestamp = sdf.format(date2);

            HashMap<String, JsonElement> extension = new HashMap<>();
            String room100key = "http://example.com/class_room_100";
            extension.put(room100key,  new JsonPrimitive("Math"));
            String room110key = "http://example.com/class_room_110";
            extension.put(room110key,  new JsonPrimitive("Science"));
            String room120key = "http://example.com/class_room_120";
            extension.put(room120key,  new JsonPrimitive("History"));
            Context context = new Context();
            context.setExtensions(extension);


            stmnt.setContext(context);
            newConnection.putStatement(stmnt, stmnt.getId());

            StatementResult result=newConnection.addFilter(room120key, extension.get(room120key).getAsString()).getStatements();
            if(result.hasMore()) {
                ListIterator<Statement> litr= result.getStatements().listIterator();
                while(litr.hasNext()){
                    System.out.println(litr.next().serialize());
                }
            }

**Comment by ljwolford** [comment]
I will not be able to test the extensions filter since it is not spec-conformant; the public LRS will return a 400 every time. However, here is an example of using the since and until filters with existing statements in the public ADL LRS. Please note that these filters are based off of the 'stored' time of the statement, and not the 'timestamp' of the statement.

```java
@Test
    public void testGetStatement()  throws FileNotFoundException, IOException {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
        Properties p = new Properties();
        p.load(new FileReader(new File("../jxapi/src/test/java/config/config.properties")));
        lrs_uri = p.getProperty("lrs_uri");
        username = p.getProperty("username");
        password = p.getProperty("password");
        mbox = p.getProperty("mbox");
        
        StatementClient client = new StatementClient(lrs_uri, username, password);
        
        Statement stmnt = new Statement(new Agent("test", mbox), 
                new Verb("http://example.com/tested"), 
                new Activity("http://example.com/" + UUID.randomUUID().toString()));
        System.out.println(stmnt.getId()+" "+df.format(new Date()));
        client.putStatement(stmnt, stmnt.getId());
        
        
        TimeZone tz = TimeZone.getTimeZone("UTC");
        df.setTimeZone(tz);
        String dateQuery = "2017-06-05T00:00:00Z";
        System.out.println("\nfilter by until "+dateQuery);
        System.out.println();
        Calendar date = javax.xml.bind.DatatypeConverter.parseDateTime(dateQuery);
        StatementResult result = client.filterByUntil(dateQuery).limitResults(10).getStatements();
        for (Statement s : result.getStatements()) {
            Calendar statementTimestamp = javax.xml.bind.DatatypeConverter.parseDateTime(s.getTimestamp());
            System.out.println(s.getId()+" "+s.getStored()+" "+(date.compareTo(statementTimestamp) >= 0));
        }
        
        
        dateQuery = "2017-06-06T18:33:00Z";
        System.out.println("\nfilter by since "+dateQuery);
        
        date = javax.xml.bind.DatatypeConverter.parseDateTime(dateQuery);
        result = client.filterBySince(dateQuery).limitResults(10).getStatements();
        for (Statement s : result.getStatements()) {
            Calendar statementTimestamp = javax.xml.bind.DatatypeConverter.parseDateTime(s.getTimestamp());
            // the since date should be less than (denoted by a compareTo value
            // being less than 0
            System.out.println(s.getId()+" "+s.getStored()+" "+(date.compareTo(statementTimestamp) < 0));
        }
    }
```

This yields the following results:

```
filter by until 2017-06-05T00:00:00Z
/statements?limit=10&until=2017-06-05T00:00:00Z
57dad2aa-d7ab-4b23-b4c4-eefe64e44b76 2017-06-04T23:52:55.337354+00:00 true
42a70dc3-2c30-4ab7-b82a-3d58c71905e4 2017-06-04T23:52:51.263122+00:00 true
5a46168a-feb2-4481-924d-09df275f22d4 2017-06-04T23:26:52.869333+00:00 true
8ff25e6e-c945-419a-832c-f740f5b4dd77 2017-06-04T23:26:52.775770+00:00 true
4f360168-a685-478c-abc7-e723cfa621dc 2017-06-04T23:26:52.679025+00:00 true
9ecbc1be-f2a5-48fa-899d-09b63a83824e 2017-06-04T23:25:47.633101+00:00 true
43aa189c-3061-4cdb-acb9-ab2e30ecd9f8 2017-06-04T23:21:12.400693+00:00 true
4c3253c7-c745-42e6-9fc0-572e097c0daf 2017-06-04T23:19:49.307047+00:00 true
b02da4c2-0eca-4623-aaef-767e99a6db91 2017-06-04T21:09:18.176568+00:00 true
d37e6e1b-73ee-4c84-a676-527e584b93d9 2017-06-04T21:09:16.404764+00:00 true
filter by since 2017-06-06T18:33:00Z
/statements?limit=10&since=2017-06-06T18:33:00Z
26bda3ea-e2d6-4209-8a32-2694f31dbfa9 2017-06-06T18:56:21.444008+00:00 true
4f6a8f91-74cf-48ad-a15a-34a86a014eeb 2017-06-06T18:55:30.502587+00:00 true
d0730414-5643-4837-b73b-3efe2d09d5d0 2017-06-06T18:55:19.198939+00:00 true
6c5fe5e6-c005-4c7f-851f-d7f42c554af4 2017-06-06T18:54:56.493631+00:00 true
2c13e41d-251b-4c32-b75f-89c908fc336b 2017-06-06T18:54:49.565485+00:00 true
dbfca4ce-088f-42ca-9873-125a90e2d84e 2017-06-06T18:53:32.322095+00:00 true
05253205-7660-486a-b5ec-09d80b29017c 2017-06-06T18:52:46.932953+00:00 true
af04dc63-8f1f-4da8-8006-6f7b1ee4250a 2017-06-06T18:52:25.779442+00:00 true
904dcb35-dcd7-440e-b5ad-c0b05b027682 2017-06-06T18:50:17.645840+00:00 true
3e8885a1-4d2e-4da6-a24f-0e0149ba7a81 2017-06-06T18:49:56.567254+00:00 true
```

The first section prints off the time we are using for the filter, as well as the query path being sent to the LRS. The statement IDs with their stored times are then being printed with all of their times being before the supplied until time. The next section prints off our since filter time and query path, then the stored times are the returned statements that are all after the supplied since time.

**Comment by Rialakshmi** [comment]
If LRS(Learning Locker in my case) is not properly querying, with proper querying mechanism, I will raise an issue in Learning Locker. Please do not close the issue.

**Comment by Rialakshmi** [comment]
Learning Locker has replied to my query to use http://docs.learninglocker.net/statements_api/#aggregate. Have you implemented this functionality in jar? Will you be able to set filter for object extension with the given URL?
FilterBySince is sometimes working, the same code sometimes do not work. FilterByUntil is working but for few values of timestamp only.
addFilter by Object Extension is priority for me.
Will you be able to help?

**Comment by Rialakshmi** [comment]
Hi I got response from Learning Locker...
Could you please check?

Hey, so let's say I have a statement like this:
{
  "actor": {"mbox": "te...@example.com"},
  "verb": {"id": "http://www.example.com/verb"},
  "object": {
    "id": "http://www.example.com/activity",
    "definition": {
      "extensions": {
        "http://www.example.com/extension": "value"
      }
    }
  }
}

A pipeline that would match that statement's object extensions would look like this:
[
  {
    "$match": {
      "statement.object.definition.extensions.http://www%46;example%46;com/extension": "value"
    }
  }
]

Note that I have replaced the "." in the extension key to transform the extension key from "http://www.example.com/extension" to "http://www%46;example%46;com/extension". This is because the "." is reserved in Mongo for denoting nested properties.

**Comment by ljwolford** [comment]
You can use java's URLEncoder whenever you add your key or potential URI value.

```java
import java.net.URLEncoder;
StatementResult result=newConnection.addFilter(URLEncoder.encode(room120key, "UTF-8"), extension.get(room120key).getAsString()).getStatements()
```

**Comment by Rialakshmi** [comment]
I tried. It gives results. Not proper results.

**Comment by Rialakshmi** [comment]
FilterBySince and FilterByUntil are not working for all values. Request you to test and find issues. The answer given by learning Locker Team is like this.

GET http://www.example.com/api/v1/statements/aggregate?pipeline=[{
  "$match": {
    "statement.timestamp": {
      "$gt":"2015-01-01T00:00",
      "$lt":"2015-01-02T00:00"
    },
    "statement.actor.mbox": "mailto:ex@mple.com",
    "voided": false
  }
}, {
  "$project": {
    "_id": 0,
    "statement": 1
  }
}]

**Comment by ljwolford** [comment]
I'm not sure what else to say about addFilter since it is being used outside the scope of the xapi spec with a custom API that is also outside of the spec scope...this is not our issue. In regards to filterBySince and filterByUntil, that looks like another custom API outside of spec scope. Again, since and until look at the STORED field in the statement, NOT the timestamp.

**Comment by Rialakshmi** [comment]
Hi, Now i would not want to check add filter functionality. I will do it on my own, or i will try to contribute to your project after Mongo db commands properly works in Learning Locker 
[
  {
    "$match": {
      "statement.object.definition.extensions.http://www%46;example%46;com/extension": "value"
    }
  }
]

**Comment by Rialakshmi** [comment]
I was testing filterByUntil and filterBySince for STORED values only, not TIMESTAMP. Postman retrieved 605 results for the command
http://xxx.tt.yyy.com/api/v1/statements/aggregate?pipeline=[{
"$match": {
"statement.stored": {
"$gt":"2017-05-05T00:00:00.000000+00:00","$lt":"2017-05-15T00:00:00.000000+00:00"
}
}
}]
But,code 
  StatementResult result=newConnection.filterByUntil("2017-05-15T00:00:00Z").filterBySince("2017-05-05T00:00:00Z").getStatements();
retrieved 105 results only. 

There are discrepancy.

**Comment by Rialakshmi** [comment]
Please test and address issues in filterByUntil and filterBySince.

**Comment by ljwolford** [comment]
Sorry, I cannot reproduce your discrepancies. I have used the filters to hit our LRS with these since and until parameters that make the path: `/statements?since=2017-06-05T00:00:00Z&until=2017-06-06T00:00:00Z`. I then tried the same thing in Postman and got the same results.  

![capture](https://user-images.githubusercontent.com/1183373/27091456-2120ccbc-502e-11e7-8343-609fee0563ac.PNG)


The only other thing I can suggest is try to use postman to make your query against `/xapi/statements` only and see what that yields.

**Comment by Rialakshmi** [comment]
I tried your command. Its not working. There is no hard core rule like we should use /xapi/statements, and it depends upon LRS you are using. You are testing in Public LRS and I am doing in learning locker. I get the below error. 

    "error": true,
    "success": false,
    "message": "",
    "code": 404,
    "trace": "#0 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\\Routing\\RouteCollection->match(Object(Illuminate\\Http\\Request))\n#1 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\\Routing\\Router->findRoute(Object(Illuminate\\Http\\Request))\n#2 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#3 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#4 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\\Foundation\\Application->dispatch(Object(Illuminate\\Http\\Request))\n#5 /var/www/html/learninglocker/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkLegacyMiddleware.php(20): Illuminate\\Foundation\\Application->handle(Object(Illuminate\\Http\\Request), 1, true)\n#6 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Clockwork\\Support\\Laravel\\ClockworkLegacyMiddleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#7 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\\Session\\Middleware->handle(Object(Illuminate\\Http\\Request), 1, true)\n#8 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\\Cookie\\Queue->handle(Object(Illuminate\\Http\\Request), 1, true)\n#9 /var/www/html/learninglocker/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\\Cookie\\Guard->handle(Object(Illuminate\\Http\\Request), 1, true)\n#10 /var/www/html/learninglocker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\\StackedHttpKernel->handle(Object(Illuminate\\Http\\Request))\n#11 /var/www/html/learninglocker/public/index.php(49): Illuminate\\Foundation\\Application->run()\n#12 {main}"

**Comment by ljwolford** [comment]
I believe with Learning Locker the URL would be `http://{{baseUrl}}/data/xAPI/statements?until={{your date}}&since={{your date}}`. That is straight from the Learning Locker documentation. 
http://docs.learninglocker.net/postman/

All conformant LRSs will have the basic `/xapi/statements` endpoint to use.

**Comment by ljwolford** [comment]
After setting up a docker instance of Learning Locker, we have confirmed we get the same results using jXAPI since/until and postman. The full LRS URL was `http://{{doman}}/data/xAPI/statements?since=2017-06-05T00:00:00Z&until=2017-06-15T00:00:00Z`

**Comment by Rialakshmi** [comment]
Its not working. Please keep the issue open and please give me some more time to validate.
